async function main(): Promise<void> {
	const isWatch = Bun.argv.includes("--watch");

	const args = [
		"build",
		"src/main.ts",
		"--outfile=main.js",
		"--format=cjs",
		"--external=obsidian",
		"--external=electron",
		"--sourcemap=inline",
	];

	if (isWatch) {
		args.push("--watch");
	} else {
		args.push("--minify", "--banner=/* THIS IS A GENERATED/BUNDLED FILE BY BUN */");
	}

	const proc = Bun.spawn(["bun", ...args], {
		stdout: "inherit",
		stderr: "inherit",
		stdin: "inherit",
	});

	const exitCode = await proc.exited;
	process.exit(exitCode);
}

void main();
